jobs:
  pkgbase:
    vermeer: # hbsd-update -Bo ?
      - [
        "echo pkgbase vermeer test",
        "&&",
        "echo pkgbase vermeer test2",
        ]

    goldmont-plus:
      - [
          "echo pkgbase goldmont_plus test",
          "&&",
          "echo pkgbase goldmont_plus test2",
          ]

  ports:
    goldmont-plus:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_desktop_overlay -j HBSD-14-STABLE -p default -z goldmont_plus -f /usr/local/etc/poudriere.d/pkglist",
        "&&",
        "gotify push -t goldmont-plus -p 10 'Build erfolgreich'",
        "||",
        "gotify push -t goldmont-plus -p 9 'Build fehlgeschlagen'",
        ]

    vermeer:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_desktop_overlay -j HBSD-14-STABLE -p default -z vermeer -c -f /usr/local/etc/poudriere.d/pkglist",
        "&&",
        "gotify push -t vermeer -p 10 'Build erfolgreich'",
        "||",
        "gotify push -t vermeer -p 9 'Build fehlgeschlagen'",
        ]

  hbsdsrv: # build & install
    hbsdsrv-build:
      - [
        "SRCDIR=/usr/local/hbsdsrv-build",
        "&&",
        "PWD=$(pwd)",
        "&&",
        "TMPDIR=$(mktemp -d)",
        "&&",
        # Git
        "git clone 'https://github.com/Dr-Deep/hbsdsrv-build.git' ${TMPDIR}/hbsdsrv-build",
        "&&",
        # /usr/local/hbsdsrv-builder
        "rm -rfv ${SRCDIR}",
        "&&",
        "cp -Rv ${TMPDIR}/hbsdsrv-build ${SRCDIR}",
        "&&",
        # Build & Install
        "cd ${SRCDIR}",
        "&&",
        "make all",
        "&&",
        "cd ${PWD}",
        "&&",
        # Restart Service?
        "echo updated our hbsdsrv-builder!", # "/usr/sbin/service hbsdsrv_builder restart",
      ]

    hbsdsrv-www:
      - [
        "SRCDIR=/usr/local/hbsdsrv-www",
        "&&",
        "PWD=$(pwd)",
        "&&",
        "TMPDIR=$(mktemp -d)",
        "&&",
        # Git
        "git clone 'https://github.com/Dr-Deep/hbsdsrv-www.git' ${TMPDIR}/hbsdsrv-www",
        "&&",
        # /usr/local/hbsdsrv-www
        "rm -rfv ${SRCDIR}",
        "&&",
        "cp -Rv ${TMPDIR}/hbsdsrv-www ${SRCDIR}",
        "&&",
        # Build & Install
        "cd ${SRCDIR}",
        "&&",
        "make all",
        "&&",
        "cd ${PWD}",
        "&&",
        # Start Service
        "/usr/sbin/service hbsdsrv_www restart",
      ]


triggers:
  - type: git
    job: pkgbase
    git-repo-url: https://git.hardenedbsd.org/hardenedbsd/HardenedBSD
    git-branch: hardened/14-stable/master	# new branch?

  - type: git
    job: ports
    git-repo-url: https://git.hardenedbsd.org/hardenedbsd/ports
    git-branch: hardenedbsd/main

  - type: git
    job: hbsdsrv-build
    git-repo-url: https://github.com/Dr-Deep/hbsdsrv-build
    git-branch: main

  - type: git
    job: hbsdsrv-www
    git-repo-url: https://github.com/Dr-Deep/hbsdsrv-www
    git-branch: main
