jobs:
  pkgbase:
    test:
      - [
        "echo pkgbase test",
        "&&",
        "echo pkgbase test2",
        ]

  ports:
    goldmont-plus:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_overlay -j HBSD-14-STABLE -p default -z goldmont_plus -f /usr/local/etc/poudriere.d/pkglist",
        ]

    skylake:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_overlay -j HBSD-14-STABLE -p default -z skylake -f /usr/local/etc/poudriere.d/pkglist",
        ]

    lto-tests:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_overlay -j HBSD-14-STABLE -p default -z lto_test -f /usr/local/etc/poudriere.d/pkglist",
        ]

triggers:
  - type: git
    job: pkgbase
    git-repo-url: https://git.hardenedbsd.org/hardenedbsd/HardenedBSD
    git-branch: hardened/14-stable/master	

  - type: git
    job: ports
    git-repo-url: https://git.hardenedbsd.org/hardenedbsd/ports
    git-branch: hardenedbsd/main
