jobs:
  pkgbase:
    test:
      - [
        "echo pkgbase test",
        "&&",
        "echo pkgbase test2",
        ]

  ports:
    goldmont-plus:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_overlay -j HBSD-14-STABLE -p default -z goldmont_plus -f /usr/local/etc/poudriere.d/pkglist",
        "&&",
        "gotify push -t goldmont-plus -p 10 'Build erfolgreich'",
        "||",
        "gotify push -t goldmont-plus -p 9 'Build fehlgeschlagen'",
        ]

    skylake:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_overlay -j HBSD-14-STABLE -p default -z skylake -f /usr/local/etc/poudriere.d/pkglist",
        "&&",
        "gotify push -t skylake -p 10 'Build erfolgreich'",
        "||",
        "gotify push -t skylake -p 9 'Build fehlgeschlagen'",
        ]

    lto-tests:
      - [
        "poudriere ports -u -p default -p hyprland_overlay -p signal_desktop_overlay",
        "&&",
        "poudriere bulk -v -O hyprland_overlay -O signal_overlay -j HBSD-14-STABLE -p default -z lto_test -f /usr/local/etc/poudriere.d/pkglist",
        "&&",
        "gotify push -t lto_test -p 10 'Build erfolgreich'",
        "||",
        "gotify push -t lto_test -p 9 'Build fehlgeschlagen'",
        ]

  hsbdsrv-build:
    build-install:
      - [
        "TMPDIR=$(mktemp -d)",
        "&&",
        "git clone 'https://github.com/Dr-Deep/hbsdsrv-build.git' $TMPDIR/hbsdsrv-build",
        "&&",
        "go build -C $TMPDIR/hbsdsrv-build -v -x",
        "&&",
        "mv $TMPDIR/hbsdsrv-build/hbsdsrv-build /usr/local/hbsdsrv-build",
        ]

  hbsdsrv-www:
    build-install:
      - [
        "TMPDIR=$(mktemp -d)",
        "&&",
        "git clone 'https://github.com/Dr-Deep/hbsdsrv-www.git' $TMPDIR/hbsdsrv-www",
        "&&",
        "go build -C $TMPDIR/hbsdsrv-www -v -x",
        "&&",
        "mv $TMPDIR/hbsdsrv-www/hbsdsrv-www /usr/local/hbsdsrv-www",
        ]

triggers:
  - type: git
    job: pkgbase
    git-repo-url: https://git.hardenedbsd.org/hardenedbsd/HardenedBSD
    git-branch: hardened/14-stable/master	

  - type: git
    job: ports
    git-repo-url: https://git.hardenedbsd.org/hardenedbsd/ports
    git-branch: hardenedbsd/main

  - type: git
    job: hsbdsrv-build
    git-repo-url: https://github.com/Dr-Deep/hbsdsrv-build/
    git-branch: main

  - type: git
    job: hsbdsrv-www
    git-repo-url: https://github.com/Dr-Deep/hbsdsrv-www
    git-branch: main
