#!/bin/sh

# PROVIDE: hbsdsrv_builder
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

# /usr/local/etc/rc.d/hbsdsrv-builder

name="hbsdsrv_builder"
rcvar=hbsdsrv_builder_enable

load_rc_config $name

: ${hbsdsrv_builder_enable:="no"}
: ${hbsdsrv_builder_args:=""}

start_cmd="${name}_start"
stop_cmd="${name}_stop"

hbsdsrv_builder_pidfile="/var/run/${name}.pid"
hbsdsrv_builder_logfile="/var/log/${name}.log"

proc="/usr/local/hbsdsrv-builder/hbsdsrv-build"
procargs="${hbsdsrv_builder_args}"

hbsdsrv_builder_start() {
    echo "Launching hbsdsrv-builder..."
    touch ${hbsdsrv_builder_logfile}
    /usr/sbin/daemon -f -p ${hbsdsrv_builder_pidfile} -o ${hbsdsrv_builder_logfile} -t ${name} ${proc} ${procargs} || {
        echo "Failed to start ${name}"
        return 1
    }
}

hbsdsrv_builder_stop() {
    echo "Stopping hbsdsrv-builder..."
    if [ -f "${hbsdsrv_builder_pidfile}"]; then
        kill -INT "$(cat "${hbsdsrv_builder_pidfile}")" || true
    fi
}

run_rc_command "$1"
